// <auto-generated />
namespace Cassantic.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11120162 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11120162));
        
        string IMigrationMetadata.Id
        {
            get { return "201611012107295_11120162"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
